[package]
name = "example-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"nmt-rs" = {git = "https://github.com/Sovereign-Labs/nmt-rs.git"}
rand = "0.8.5"